// <auto-generated />
namespace Project_Management.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class secone : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(secone));
        
        string IMigrationMetadata.Id
        {
            get { return "201912111429533_secone"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
